sudo: required
services: 
    - docker

before_install:
    - docker build -t farisdidin/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true farisdidin/react-test npm test -- --coverage

after_success:
    - docker build -t farisdidin/multi-client  ./client 
    - docker build -t farisdidin/multi-nginx  ./nginx
    - docker build -t farisdidin/multi-server  ./server
    - docker build -t farisdidin/multi-worker  ./worker
    #Login to docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Push 
    - docker push farisdidin/multi-client
    - docker push farisdidin/multi-nginx
    - docker push farisdidin/multi-server
    - docker push farisdidin/multi-worker
